---
title: "Course work"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

## Summary

You will have three individual assignments, six seminar submissions, and one group project: 

* One intro assignment (5%)
* Six in-seminar submissions (10% total; 2% each after dropping the lowest score)
* One paper review (5%) 
* One analysis assignment (30%)
* Final group project (50%) which contains multiple parts. 

<font color="red">**Deadlines are all by 11:59 pm (Pacific time) on the due date. Any submission or modification after the due date will not be graded unless you have requested an extension**</font>. If you anticipate having trouble meeting a deadline and need to request an extension/academic concession please reach out via email.

For detailed instructions on how to submit your work, see the [submission guide](submission_guide.html). 

## Timeline Overview

For a visual summary, click [here](timeline.html).

```{r, echo=FALSE, warning=FALSE}
suppressPackageStartupMessages(library(tidyverse))
assn <- read.csv("course-admin/assn_2023.csv")
assn <- assn %>% 
  select(Category, content, start) %>%
  rename(Assignment = content, `Due Date` = start) %>%
  mutate(`Due Date` = as.Date(`Due Date`, "%Y-%m-%d")) %>%
  arrange(`Due Date`) %>% 
  mutate(`Due Date` = format(`Due Date`, "%a %b %d"))
knitr::kable(assn)
```

# Assignments Overview

## Intro assignment (5%)

This assignment is designed to give you independent practice in the workflow used for completing and submitting course work: committing and pushing files to GitHub, formatting an R Markdown document, using R to do simple analyses, and writing about your results. Grade point values are listed in the assignment.

The instructions and questions are available [here](https://github.com/STAT540-UBC/intro-assignment/blob/main/intro_assignment.md).

## Seminar completion (10%)

You will submit short "deliverables" for six seminars: 1, 2 (split into two parts - Seminar 2a and 2b together count as one deliverable), 3, 4, 5, and 8. These deliverables give practical experience applying the knowledge that will be helpful on the homework assignment, final project, and (hopefully) your future research. Each of these six Seminar session deliverables is weighted equally, but the lowest score will be dropped (so that the 5 deliverables with highest score will each count for 2% of the final grade). Seminar deliverables are due on the Monday following the TA-led session for that seminar. See the [Seminars page](seminars.html) for the submission materials.

## Paper critique (5%)

Each student should review and provide a 500-700 word critique this paper:

* [Comparative Transcriptome Profiling of Human Foreskin Fibroblasts Infected with the Sylvio and Y Strains of *Trypanosoma cruzi*](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0159197) by Houston-Ludlam et al (2016)

Please see [**critique rubric**](critique.html) for detailed instructions on this task. 

## Analysis assignment (30%)

This assignment will assess your understanding of the seminar and lecture materials. Start early because this assignment will take time to fully work through. Use the issues in the Discussion repo and the seminar time to ask questions. You will find most of the analysis workflow of the assignment in the seminar materials. 

The instruction and questions and are available [here](https://github.com/STAT540-UBC/analysis-assignment/blob/main/analysis_assignment.md).

The grade point values for each question are listed right in the assignment.


## Final group project (50%)

### General principles

Identify a biological question of interest and a relevant dataset. Develop and apply a statistical approach that allows you to use the dataset to answer the question.

We assume the biological question and data fall in the general area of high-throughput, large-scale biological investigations *targeted by the course*. Beyond that, it is wide open: methylation, SNPs, miRNAs, CNVs, RNA-Seq, CHiP-Seq, gene networks, ... it's fair game. Avoid a dataset that doesn't have any/much quantitative data, i.e. contains only sequence or discrete data. If you are using published data, it is critical to *be clear about how your project differs from previous literature*.

Note that definitive answers are not necessarily expected. Rather, aim to provide a critical appraisal of the data, the analytical approach, and the results. You will have to handle the competing pressures to "get it right" and "get it done". Shortcomings of the data, misfits between the data or the biological question and the statistical model, etc. are inevitable. Your goal is to identify such issues and discuss them critically, without becoming paralyzed. Demonstrate understanding of the statistical concepts and methods that are the foundation of your analytical approach.

We assume the analytical and computing task will have a substantial statistical component, probably enacted via R. So beware of a major analytical or computational undertaking that is, nonetheless, not statistical (example: constructing a database). Creating useful data visualizations can be absolutely vital and is arguably statistical, but your analysis should go beyond merely creating pretty pictures (but please do include some!). Key concepts, at least some of which should come up in your analysis:

 * the (hypothesized, probably artificial) data-generating model

 * background variation, variance, signal to noise ratio, estimates and their associated standard error

 * relationship between biological factors and experimental factors, apparent relative importance in terms of "explaining" observed data

 * attention to large-scale inference, e.g. control of family-wise error rate or false discovery rate
 
 
### Data considerations 

#### Appropriate use of data

If your project involves using unpublished data, ensure your plans are known to the data providers (e.g., your supervisors), and think about implications for publishing - are you are bringing the project team in as collaborators in effect? Are you planning to publish the results of your project, and if so who will be the co-authors? It is best to deal with these questions at the outset of the project.

#### Privacy of project data

The projects are not made public (other than an oral presentation of your work in front of your classmates, which **will be recorded** and made available only to the teaching team and registered students in the course). The project report materials are loaded into GitHub, the secure site we use to manage the course. The course staff and instructors are the only people who have access to the project GitHub repo other than the other members of the project group. The data used can be uploaded to the project, but this can limited or omitted if there are special concerns about privacy etc. - it's primarily the code and write-up about the results that needs to be provided for evaluation.

You can read Github's [security](https://help.github.com/articles/github-security/) and [privacy](https://help.github.com/articles/github-privacy-statement/) policies.

### Group makeup

Groups will be formed by the instructional team following the results of an in class survey, and posted in the Discussion repo. Groups will have a target size of 4 members. Groups will be formed with priority for diversity in terms of backgrounds. In practice, this probably means the team members come from a mix of programs/departments. We will try to honour requests for working with specific team mates, and you may come talk to us immediately after receiving group assignments if you'd like to make a change.

### Deliverables

Details and grading rubrics for each component of the final group project can be found on the [**Group project rubrics page**](group_project_rubrics.html).

* [Project Proposal Lightning Talks (5%)](group_project_rubrics.html#project-proposal-lightning-talks-5-pts)
* [Written Proposal (5%)](group_project_rubrics.html#written-proposal-5-pts)
* [Progress report (8%)](group_project_rubrics.html#progress-report-8-pts)
* [Final report (10%)](group_project_rubrics.html#final-report-10-pts)
* [Oral presentation (15%)](group_project_rubrics.html#oral-presentation-15-pts) - A Detailed rubric can be found [here](course-admin/ProjectPresentationRubric.pdf)
* [Individual report (7%)](group_project_rubrics.html#individual-report-7-pts)
