---
title: "Frequently Asked Questions"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

## Registration

### When is the course offered?

January-April of each academic year. 

### I am not in one of the three cross-listed grad programs (STAT/BIOF/GSAT), but I would like to take this course. Can you grant me permission to register?

This course is primarily aimed at graduate students from three grad programs: STAT (Statistics), BIOF (Bioinformatics), and GSAT (Genome Sciences and Technology), and will not allow other students to register without permission. This is because the course is a recommended elective for these degree programs. As the course has become increasingly popular with students from other grad programs, we maintain a waitlist. We invite you to register for the waitlist **as soon as possible**, as we fill any available seats not occupied by STAT/BIOF/GSAT students from the waitlist (first-come, first-served) close to the start of the term.
 
### I am on the waitlist. Will I get a spot in the course?

If there are seats available, we will fill them from the waitlist (first-come, first-served) close to the start of the term. If there are no seats available, unfortunately we are not able to increase the class capacity.

### Can I audit the course?

If there's a seat available for you, then yes! Unfortunately, you'll still have to join the waitlist if you're not a STAT/BIOF/GSAT student. Auditing still counts as a seat in the class, so auditing is not a way around the course capacity. Auditors are expected to complete all coursework (pass/fail) except the final project.

### Can I just 'sit in' the course without enrolling?

Unfortunately not. Besides room capacity constraints, we just don't have enough human resources (instructors, TAs) to accommodate students who are not registered. But you are still welcome to check out all the lecture notes, seminar worksheets, and resources freely available on this website!

## Prerequisites

### I have a strong background in biology, and am proficient in R, but have only had one university-level statistics course. Is STAT 540 for me?

Yes! None of us is an expert in all areas. This course is designed for those who have at least some entry-level experience in statistics, biology, and programming, but it is expected that each student will have differing degrees of strength across these areas. This is actually ideal for the group project, since we form teams with complementary areas of expertise.

### I have a strong background in statistics, am proficient in R, but haven't taken any biology or genetics courses. Is STAT 540 for me?

Yes! See previous question :)

### I have never used R before. Is STAT 540 for me?

If you have some background in statistics and/or biology, then it could be! But be prepared for a steep learning curve with a lot of self-guided learning, especially if you don't have experience with other programing languages. 