---
title: "Seminars"
---


```{r include = FALSE}
library(dplyr)
library(stringr)
library(glue)
library(here)
library(RCurl)
```

```{r include = FALSE}
# Import schedule
rawdat <- read.csv(file.path("course-admin", "schedule.csv"), stringsAsFactors = FALSE, colClasses = list(course = 'factor', dow = 'factor'))
rawdat$course <- as.factor(rawdat$course)

# Seminar meetings 
rawdat_sm <- rawdat[rawdat$course == "STAT540-Seminar",]

sdat <- rawdat_sm %>%
  mutate(ugly_date = ISOdate(2024, match(month, month.name), day),
         date = sprintf("%s %s %s",
                        dow, 
                        months(ugly_date, abbreviate = TRUE),
                        day))
sdat %>% head(3)

## link to the page of any seminar where such exists
smdat <- data.frame(repo = sprintf("https://github.com/STAT540-UBC/seminar-%02d", 
                                   c(1, 2, 2, seq(3,11))))
smdat$repo[2:3] <- paste0(smdat$repo[2:3], c("a", "b"))
smdat$lect <- gsub("https://github.com/STAT540-UBC/", 
                   "", smdat$repo)
smdat$lect <- gsub("-0", 
                   "-", smdat$lect)
sdat <- sdat %>% left_join(smdat, by="lect")

sdat <- sdat %>% split(sdat$course) 
sdat <- sdat[["STAT540-Seminar"]]
```


### Seminars

**Time**: Tuesday 12:30pm - 1:30pm

**Location**: Building and room number listed on Canvas

We strongly recommend reading the seminar materials prior to attending each seminar

```{r results = 'asis', echo = FALSE}
sdat <- sdat %>%
  mutate(name = gsub("-", " ", gsub("s", "S", lect))) %>%
  mutate(name = gsub("No Seminar", "", name))

sdat <- sdat %>% 
  mutate(exists = url.exists(repo)) %>%
  mutate(repo = ifelse(exists, repo, "")) %>%
  mutate(link = ifelse(exists,
                       paste0("[", name, "](", repo, ")"),
                       name))

sdat <- sdat %>% select(date, link, raw_notes, instructor) %>%
            dplyr::rename(Date=date, Repo= link,
                          Topic = raw_notes, 
                          `Lead TA` = instructor) %>%
  mutate(Repo = as.character(Repo)) %>%
  data.frame()

knitr::kable(sdat, format="html") %>% 
  kableExtra::column_spec(1:2, width = "6em") %>%
  kableExtra::kable_styling(full_width = TRUE)
```
